import type { Equipment, Student } from "./types"

export const initialEquipment: Equipment[] = [
  {
    id: "eq-001",
    name: "Laptop Dell XPS 13",
    nameEn: "Dell XPS 13 Laptop",
    type: "Laptop",
    status: "available",
    location: "Room 101",
    lastMaintenance: new Date().toISOString(),
    nextMaintenance: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    qrCode: "eq001-xyz",
    checkedOutBy: null,
    checkedOutAt: null,
    group: "Компьютеры",
    owner: "",
    room: 101,
    building: 1,
    lab: 1
  },
  {
    id: "eq-002",
    name: "Projector Epson",
    nameEn: "Epson Projector",
    type: "Projector",
    status: "available",
    location: "Room 101",
    lastMaintenance: new Date().toISOString(),
    nextMaintenance: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    qrCode: "eq002-xyz",
    checkedOutBy: null,
    checkedOutAt: null,
    group: "Проекторы",
    owner: "",
    room: 101,
    building: 1,
    lab: 1
  },
  {
    id: "eq-003",
    name: "iPad Pro 12.9\"",
    nameEn: "iPad Pro 12.9\"",
    type: "Tablet",
    status: "available",
    location: "Room 101",
    lastMaintenance: new Date().toISOString(),
    nextMaintenance: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    qrCode: "eq003-xyz",
    checkedOutBy: null,
    checkedOutAt: null,
    group: "Планшеты",
    owner: "",
    room: 101,
    building: 1,
    lab: 1
  },
  {
    id: "eq-004",
    name: "Digital Camera Canon",
    nameEn: "Canon Digital Camera",
    type: "Camera",
    status: "available",
    location: "Room 101",
    lastMaintenance: new Date().toISOString(),
    nextMaintenance: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    qrCode: "eq004-xyz",
    checkedOutBy: null,
    checkedOutAt: null,
    group: "Камеры",
    owner: "",
    room: 101,
    building: 1,
    lab: 1
  },
  {
    id: "eq-005",
    name: "Microscope",
    nameEn: "Microscope",
    type: "Lab Equipment",
    status: "maintenance",
    location: "Room 101",
    lastMaintenance: new Date().toISOString(),
    nextMaintenance: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    qrCode: "eq005-xyz",
    checkedOutBy: null,
    checkedOutAt: null,
    group: "Лабораторное оборудование",
    owner: "",
    room: 101,
    building: 1,
    lab: 1
  },
  {
    id: "eq-006",
    name: "VR Headset",
    nameEn: "VR Headset",
    type: "VR Equipment",
    status: "available",
    location: "Room 101",
    lastMaintenance: new Date().toISOString(),
    nextMaintenance: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    qrCode: "eq006-xyz",
    checkedOutBy: null,
    checkedOutAt: null,
    group: "VR оборудование",
    owner: "",
    room: 101,
    building: 1,
    lab: 1
  }
]

export const initialStudents: Student[] = [
  {
    id: "st-001",
    name: "Anna Petrova",
    group: "CS-101",
    hasAccess: true,
  },
  {
    id: "st-002",
    name: "Ivan Ivanov",
    group: "CS-101",
    hasAccess: true,
  },
  {
    id: "st-003",
    name: "Maria Sidorova",
    group: "CS-102",
    hasAccess: false,
  },
  {
    id: "st-004",
    name: "Alexey Smirnov",
    group: "CS-102",
    hasAccess: true,
  },
  {
    id: "st-005",
    name: "Elena Volkova",
    group: "CS-103",
    hasAccess: true,
  },
]

